sonar.projectKey=apiClinical
sonar.working.directory=D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\FreeLance\\ApiClinicalMed\\WebApplication1
sonar.pullrequest.cache.basepath=D:\\FreeLance\\ApiClinicalMed\\WebApplication1
sonar.sources=\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\.dockerignore"

5CB099E9-C9D3-40D9-B7F0-45135B705419.sonar.projectKey=apiClinical:5CB099E9-C9D3-40D9-B7F0-45135B705419
5CB099E9-C9D3-40D9-B7F0-45135B705419.sonar.projectName=WebApplication1
5CB099E9-C9D3-40D9-B7F0-45135B705419.sonar.projectBaseDir=D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1
5CB099E9-C9D3-40D9-B7F0-45135B705419.sonar.sourceEncoding=utf-8
5CB099E9-C9D3-40D9-B7F0-45135B705419.sonar.tests=
5CB099E9-C9D3-40D9-B7F0-45135B705419.sonar.sources=\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Controllers\\AppointmentMedicalController\\AppointmentMedicalController.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Controllers\\AuthController\\AuthController.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Controllers\\ConsultationMedicalController\\ConsultationMedicalController.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Controllers\\DoctorController\\DoctorController.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Controllers\\HealthApiController\\HealthController.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Controllers\\LoginController\\LoginController.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Controllers\\LogoutController\\LogoutController.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Controllers\\PatientController\\PatientController.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Controllers\\PrescriptionController\\PrescriptionController.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Core\\Entities\\Doctor.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Core\\Entities\\MedicalConsultation.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Core\\Entities\\Patient.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Core\\Entities\\Prescription.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Core\\Entities\\TypeAppointmentMedical.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Core\\Entities\\User.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Consultation\\CreateConsultationDto.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Consultation\\FinishConsultationDto.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Consultation\\ResponseConsultByUser.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Consultation\\ResponseCreateConsultation.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Doctor\\CreateDoctorDto.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Doctor\\DoctorResponseDto.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Doctor\\UpdateDoctorDto.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Email\\SendEmailAppointmentDTO.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Login\\LoginDto.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Login\\ResponseLoginDto.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Patient\\CreatePatientDto.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Patient\\PatientResponseDto.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\DTOS\\Patient\\UpdatePatientDto.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Enums\\StatusConsultation.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Enums\\TypeUser.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Extensions\\ExceptionMiddlewareExtensions.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Extensions\\JwtCollectionExtensions.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Extensions\\ServiceCollectionExtensions.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Infrastructure\\Data\\AppDbContext.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Middleware\\ExceptionMiddleware.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\20250417192444_Initial.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\20250417192444_Initial.Designer.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\20250603000121_createConsultation.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\20250603000121_createConsultation.Designer.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\20250811215817_AddPrescriptionEntityChanges.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\20250811215817_AddPrescriptionEntityChanges.Designer.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\20250811230710_alterTypeColunm.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\20250811230710_alterTypeColunm.Designer.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\20250822170724_removeColunsMedicalConsultation.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\20250822170724_removeColunsMedicalConsultation.Designer.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Migrations\\AppDbContextModelSnapshot.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Program.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\ConsultationRepository\\ConsultationRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\ConsultationRepository\\IConsultationRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\DoctorRepository\\DoctorRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\DoctorRepository\\IDoctorRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\PatientRepository\\IPatientRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\PatientRepository\\PatientRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\PrescriptionRepository\\IPrescriptionRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\PrescriptionRepository\\PrescriptionRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\TypeAppointmentMedicalRepository\\AppointmentMedicalRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\TypeAppointmentMedicalRepository\\IAppointmentMedicalRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\UserRepository\\IUserRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Repositories\\UserRepository\\UserRepository.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\ConsultationService\\ConsultationService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\ConsultationService\\IConsultationService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\DoctorService\\DoctorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\DoctorService\\IDoctorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\EmailService\\EmailService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\EmailService\\IEmailService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\LoginService\\ILoginService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\LoginService\\LoginService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\MeetingService\\IMeetingService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\MeetingService\\MeetingService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\PatientService\\IPatientService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\PatientService\\PatientService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\PrescriptionService\\IPrescriptionService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\PrescriptionService\\PrescriptionService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\TypeAppointmentMedicalService\\ITypeAppointmentService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\TypeAppointmentMedicalService\\TypeAppointmentService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Utils\\FindUser.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Utils\\IJwtService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Utils\\IPasswordHasher.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Utils\\JwtService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Utils\\PasswordHasher.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\AppointmentMedicalValidator\\AppointmentMedicalValidatorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\AppointmentMedicalValidator\\IAppointmentMedicalValidatorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\ConsultationMedicalValidator\\ConsultationMedicalValidatorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\ConsultationMedicalValidator\\IConsultationMedicalValidatorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\CpfValidator\\CpfValidatorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\CpfValidator\\ICpfValidatorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\CrmValidator\\CrmValidator.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\CrmValidator\\ICrmValidator.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\EmailValidator\\EmailValidatorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\EmailValidator\\IEmailValidatorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\SusCardValidator\\ISusCardValidatorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\Validators\\SusCardValidator\\SusCardValidatorService.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\obj\\Debug\\net9.0\\WebApplication1.GlobalUsings.g.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\obj\\Debug\\net9.0\\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\obj\\Debug\\net9.0\\WebApplication1.AssemblyInfo.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\obj\\Debug\\net9.0\\WebApplication1.MvcApplicationPartsAssemblyInfo.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\appsettings.Development.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\appsettings.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Services\\EmailService\\templates\\AppointmentEmail.html",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\.gitignore",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Dockerfile",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\Properties\\launchSettings.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\obj\\project.assets.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\obj\\project.packagespec.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\obj\\WebApplication1.csproj.nuget.dgspec.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\bin\\Debug\\net9.0\\appsettings.Development.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\bin\\Debug\\net9.0\\appsettings.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\bin\\Debug\\net9.0\\WebApplication1.deps.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\bin\\Debug\\net9.0\\WebApplication1.runtimeconfig.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\bin\\Debug\\net9.0\\WebApplication1.staticwebassets.endpoints.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\obj\\Debug\\net9.0\\staticwebassets.build.endpoints.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\obj\\Debug\\net9.0\\staticwebassets.build.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\obj\\Debug\\net9.0\\WebApplication1.sourcelink.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1\\bin\\Debug\\net9.0\\Services\\EmailService\\templates\\AppointmentEmail.html"

5CB099E9-C9D3-40D9-B7F0-45135B705419.sonar.cs.analyzer.projectOutPaths=\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\.sonarqube\\out\\0"
5CB099E9-C9D3-40D9-B7F0-45135B705419.sonar.cs.roslyn.reportFilePaths=\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\.sonarqube\\out\\0\\Issues.json"
5CB099E9-C9D3-40D9-B7F0-45135B705419.sonar.cs.scanner.telemetry=\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\.sonarqube\\out\\0\\Telemetry.json"

5CB099E9-C9D3-40D9-B7F0-45135B705419.sonar.working.directory=D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\.sonarqube\\out\\.sonar\\mod0
2E235709-C3E0-4D96-98B8-3A7DE88E1BCA.sonar.projectKey=apiClinical:2E235709-C3E0-4D96-98B8-3A7DE88E1BCA
2E235709-C3E0-4D96-98B8-3A7DE88E1BCA.sonar.projectName=WebApplication1.Tests
2E235709-C3E0-4D96-98B8-3A7DE88E1BCA.sonar.projectBaseDir=D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests
2E235709-C3E0-4D96-98B8-3A7DE88E1BCA.sonar.sourceEncoding=utf-8
2E235709-C3E0-4D96-98B8-3A7DE88E1BCA.sonar.sources=
2E235709-C3E0-4D96-98B8-3A7DE88E1BCA.sonar.tests=\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\obj\\project.assets.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\obj\\project.packagespec.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\obj\\WebApplication1.Tests.csproj.nuget.dgspec.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\bin\\Debug\\net9.0\\appsettings.Development.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\bin\\Debug\\net9.0\\appsettings.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\bin\\Debug\\net9.0\\WebApplication1.deps.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\bin\\Debug\\net9.0\\WebApplication1.runtimeconfig.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\bin\\Debug\\net9.0\\WebApplication1.staticwebassets.endpoints.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\bin\\Debug\\net9.0\\WebApplication1.Tests.deps.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\bin\\Debug\\net9.0\\WebApplication1.Tests.runtimeconfig.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\obj\\Debug\\net9.0\\WebApplication1.Tests.sourcelink.json",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\bin\\Debug\\net9.0\\Services\\EmailService\\templates\\AppointmentEmail.html",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\Helpers\\UserFactory.cs",\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\WebApplication1.Tests\\LoginServiceTest\\LoginServiceTest.cs"

2E235709-C3E0-4D96-98B8-3A7DE88E1BCA.sonar.cs.analyzer.projectOutPaths=\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\.sonarqube\\out\\1"
2E235709-C3E0-4D96-98B8-3A7DE88E1BCA.sonar.cs.roslyn.reportFilePaths=\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\.sonarqube\\out\\1\\Issues.json"
2E235709-C3E0-4D96-98B8-3A7DE88E1BCA.sonar.cs.scanner.telemetry=\
"D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\.sonarqube\\out\\1\\Telemetry.json"

2E235709-C3E0-4D96-98B8-3A7DE88E1BCA.sonar.working.directory=D:\\FreeLance\\ApiClinicalMed\\WebApplication1\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:32768
sonar.visualstudio.enable=false

sonar.modules=5CB099E9-C9D3-40D9-B7F0-45135B705419,2E235709-C3E0-4D96-98B8-3A7DE88E1BCA

