// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Infrastructure.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250822170724_removeColunsMedicalConsultation")]
    partial class removeColunsMedicalConsultation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Core.Entities.MedicalConsultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("agreementDiscount")
                        .HasColumnType("double precision");

                    b.Property<string>("consultationLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("consultationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("doctorId")
                        .HasColumnType("integer");

                    b.Property<int?>("idPrescription")
                        .HasColumnType("integer");

                    b.Property<string>("justificationUpdate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("patientId")
                        .HasColumnType("integer");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<int>("typeAppointmentMedical")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MedicalConsultation");
                });

            modelBuilder.Entity("WebApplication1.Core.Entities.Prescription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("crmDoctor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("doctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dosageRemedy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("frequencyRemedy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("patientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("remedyPrescription")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("validityPrescription")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("WebApplication1.Core.Entities.TypeAppointmentMedical", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("value")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("TypeAppointmentMedical");
                });

            modelBuilder.Entity("WebApplication1.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("birthDate")
                        .HasColumnType("date");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("complement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("typeUser")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WebApplication1.Core.Entities.Doctor", b =>
                {
                    b.HasBaseType("WebApplication1.Core.Entities.User");

                    b.Property<string>("areaSpecialty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("crm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Core.Entities.Patient", b =>
                {
                    b.HasBaseType("WebApplication1.Core.Entities.User");

                    b.PrimitiveCollection<List<string>>("familyHistoryDisease")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("medicalAgreements")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("messagePhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("susCard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Core.Entities.Doctor", b =>
                {
                    b.HasOne("WebApplication1.Core.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("WebApplication1.Core.Entities.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Core.Entities.Patient", b =>
                {
                    b.HasOne("WebApplication1.Core.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("WebApplication1.Core.Entities.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
